name: model_json
description: DB model managment library
homepage: https://github.com/da-the-dev/model_json
version: 1.0.2

environment:
  sdk: '^3.0.0'
dependencies:
  equatable: ^2.0.5
  type_plus: ^2.0.1
dev_dependencies:
  test: ^1.24.4
